#!/bin/bash

root_pwd=$(sudo cat /etc/yunohost/mysql)
domain=$(sudo yunohost app setting piwik domain)
admin=$(sudo yunohost app setting piwik admin)
path=$(sudo yunohost app setting piwik path)
geoip_plugin=$(sudo yunohost app setting piwik geoip_plugin)
log_analyse=$(sudo yunohost app setting piwik log_analyse)

# Suppression de la base de donnée et son user
mysql -u root -p$root_pwd -e "DROP DATABASE piwik ; DROP USER piwik@localhost ;"
# Suppression du dossier
sudo rm -rf /var/www/piwik
# Suppression de la configuration nginx
sudo rm -f /etc/nginx/conf.d/$domain.d/piwik.conf
# Suppression de la config php-fpm
sudo rm -f /etc/php5/fpm/pool.d/piwik.conf

if [ "$geoip_plugin" = "Yes" ]
then
	# Suppression du config ini php-fpm
	sudo rm -f /etc/php5/fpm/conf.d/20-piwik.ini

	# Retirer les lignes du crontab pour geoip
 	path_no_slash=$(echo $path | cut -d '/' -f 2)
	sudo crontab -l -u www-data | sudo tee crontab_file
	sudo sed -i "/base de donnée GeoIP pour piwik/d" crontab_file
	sudo sed -i "/$path_no_slash\/misc\/geoip\/maj_geoip.sh/d" crontab_file
	sudo crontab -u www-data crontab_file
fi

if [ "$log_analyse" = "Yes" ]
then
	# Retirer les lignes du crontab pour log_analitics
 	path_no_slash=$(echo $path | cut -d '/' -f 2)
	sudo crontab -l -u www-data | sudo tee crontab_file
	sudo sed -i "/logs nginx pour piwik/d" crontab_file
	sudo sed -i "/$path_no_slash\/misc\/log-analytics\/manage_import.sh/d" crontab_file
	sudo crontab -u www-data crontab_file

    # Retirer la commande dans le logrotate
	sudo sed -i "/$path_no_slash\/misc\/log-analytics\/manage_import.sh/d" /etc/logrotate.d/nginx
fi

# Reload Nginx and php, and regenerate SSOwat conf
sudo service nginx reload
sudo yunohost app ssowatconf
sudo service php5-fpm reload
